/**
 * @beginner-module: 源码导读
 * 本文件属于 DOM 绑定层，负责创建/更新 DOM 属性、事件、表单值或宿主配置。
 * 阅读建议：先看这些中文注释建立概念，再回到代码名和类型名理解真实实现。
 */
// @beginner: 声明 roles：保存当前步骤需要读取或更新的数据。
const roles: Record<string, 0> = {
  alert: 0,
  alertdialog: 0,
  application: 0,
  article: 0,
  banner: 0,
  button: 0,
  cell: 0,
  checkbox: 0,
  columnheader: 0,
  combobox: 0,
  complementary: 0,
  contentinfo: 0,
  dialog: 0,
  document: 0,
  form: 0,
  grid: 0,
  gridcell: 0,
  heading: 0,
  img: 0,
  link: 0,
  list: 0,
  listbox: 0,
  listitem: 0,
  main: 0,
  menu: 0,
  menuitem: 0,
  navigation: 0,
  option: 0,
  progressbar: 0,
  radio: 0,
  radiogroup: 0,
  region: 0,
  row: 0,
  rowgroup: 0,
  rowheader: 0,
  scrollbar: 0,
  search: 0,
  separator: 0,
  slider: 0,
  spinbutton: 0,
  status: 0,
  switch: 0,
  tab: 0,
  table: 0,
  tablist: 0,
  tabpanel: 0,
  textbox: 0,
  timer: 0,
  toolbar: 0,
  tooltip: 0,
  tree: 0,
  treegrid: 0,
  treeitem: 0,
};

export default roles;
