/**
 * This module is Node-only.
 */
// 这里的优化只在 Node 侧编译流程里启用，浏览器内联编译不会走到它。
import {
  // createStaticVNode 对应的 helper symbol。
  CREATE_STATIC,
  // 缓存表达式节点类型。
  type CacheExpression,
  // 常量级别枚举。
  ConstantTypes,
  // 元素节点类型。
  type ElementNode,
  // 标签类型枚举。
  ElementTypes,
  // 表达式节点类型。
  type ExpressionNode,
  // hoist 阶段使用的 transform 类型。
  type HoistTransform,
  // 命名空间枚举。
  Namespaces,
  // AST 节点类型枚举。
  NodeTypes,
  // 普通原生元素节点类型。
  type PlainElementNode,
  // 简单表达式节点类型。
  type SimpleExpressionNode,
  // 模板子节点联合类型。
  type TemplateChildNode,
  // 文本调用节点类型。
  type TextCallNode,
  // transform 上下文类型。
  type TransformContext,
  // 创建函数调用表达式。
  createCallExpression,
  // 查找指令。
  findDir,
  // 判断参数是否是指定静态值。
  isStaticArgOf,
} from '@vue-source/compiler-core'
import {
  // HTML 转义。
  escapeHtml,
  // 判断是否数组。
  isArray,
  // 判断布尔属性。
  isBooleanAttr,
  // 各平台已知合法属性判断。
  isKnownHtmlAttr,
  isKnownMathMLAttr,
  isKnownSvgAttr,
  // 运行时类型判断工具。
  isString,
  isSymbol,
  // void tag 判断。
  isVoidTag,
  // 生成 map 函数。
  makeMap,
  // class / style 规范化与序列化工具。
  normalizeClass,
  normalizeStyle,
  stringifyStyle,
  // 插值值转字符串。
  toDisplayString,
} from '@vue-source/shared'

// 达到以下阈值时，才值得把一段静态树压缩成 createStaticVNode。
export enum StringifyThresholds {
  // 一个 chunk 里带绑定的元素达到 5 个以上时收益明显。
  ELEMENT_WITH_BINDING_COUNT = 5,
  // 一个 chunk 总节点数达到 20 个以上时收益明显。
  NODE_COUNT = 20,
}

// 能被字符串化的节点：普通原生元素和文本调用节点。
type StringifiableNode = PlainElementNode | TextCallNode

/**
 * Regex for replacing placeholders for embedded constant variables
 * (e.g. import URL string constants generated by compiler-sfc)
 */
// 用于把 "__VUE_EXP_START__x__VUE_EXP_END__" 重新还原成字符串拼接表达式。
const expReplaceRE = /__VUE_EXP_START__(.*?)__VUE_EXP_END__/g

/**
 * Turn eligible hoisted static trees into stringified static nodes, e.g.
 *
 * ```js
 * const _hoisted_1 = createStaticVNode(`<div class="foo">bar</div>`)
 * ```
 *
 * A single static vnode can contain stringified content for **multiple**
 * consecutive nodes (element and plain text), called a "chunk".
 * `@vue-source/runtime-dom` will create the content via innerHTML in a hidden
 * container element and insert all the nodes in place. The call must also
 * provide the number of nodes contained in the chunk so that during hydration
 * we can know how many nodes the static vnode should adopt.
 *
 * The optimization scans a children list that contains hoisted nodes, and
 * tries to find the largest chunk of consecutive hoisted nodes before running
 * into a non-hoisted node or the end of the list. A chunk is then converted
 * into a single static vnode and replaces the hoisted expression of the first
 * node in the chunk. Other nodes in the chunk are considered "merged" and
 * therefore removed from both the hoist list and the children array.
 *
 * This optimization is only performed in Node.js.
 */
// 把符合条件的静态提升节点进一步压缩成字符串形式的静态 VNode。
export const stringifyStatic: HoistTransform = (children, context, parent) => {
  // slot 内容依赖插槽作用域，不能安全做这种跨节点静态字符串化。
  // bail stringification for slot content
  if (context.scopes.vSlot > 0) {
    return
  }

  // 某些父节点的 children 整体已经被包进缓存表达式，需要特殊处理替换逻辑。
  const isParentCached =
    parent.type === NodeTypes.ELEMENT &&
    parent.codegenNode &&
    parent.codegenNode.type === NodeTypes.VNODE_CALL &&
    parent.codegenNode.children &&
    !isArray(parent.codegenNode.children) &&
    parent.codegenNode.children.type === NodeTypes.JS_CACHE_EXPRESSION

  // 当前 chunk 内累计的 DOM 节点数。
  let nc = 0 // current node count
  // 当前 chunk 内“带绑定的元素”数量。
  let ec = 0 // current element with binding count
  // 正在累积、准备合并的连续静态节点片段。
  const currentChunk: StringifiableNode[] = []

  const stringifyCurrentChunk = (currentIndex: number): number => {
    // 只有达到阈值的 chunk 才真正执行字符串化，太小反而可能不划算。
    if (
      nc >= StringifyThresholds.NODE_COUNT ||
      ec >= StringifyThresholds.ELEMENT_WITH_BINDING_COUNT
    ) {
      // combine all currently eligible nodes into a single static vnode call
      // 把当前 chunk 里的多个节点序列化成一段 HTML 字符串，并创建 createStaticVNode 调用。
      const staticCall = createCallExpression(context.helper(CREATE_STATIC), [
        JSON.stringify(
          currentChunk.map(node => stringifyNode(node, context)).join(''),
        ).replace(expReplaceRE, `" + $1 + "`),
        // the 2nd argument indicates the number of DOM nodes this static vnode
        // will insert / hydrate
        // 第二个参数是这个静态块对应的实际 DOM 节点数量，hydration 时要用。
        String(currentChunk.length),
      ])

      // 第一个节点会被保留并替换成 static vnode，其余节点会被合并删除。
      const deleteCount = currentChunk.length - 1

      if (isParentCached) {
        // if the parent is cached, then `children` is also the value of the
        // CacheExpression. Just replace the corresponding range in the cached
        // list with staticCall.
        // 父 children 自身就是缓存值时，直接在 children 数组中整段替换。
        children.splice(
          currentIndex - currentChunk.length,
          currentChunk.length,
          // @ts-expect-error
          staticCall,
        )
      } else {
        // replace the first node's hoisted expression with the static vnode call
        // 否则把 chunk 首节点对应的缓存表达式 value 改成 staticCall。
        ;(currentChunk[0].codegenNode as CacheExpression).value = staticCall
        if (currentChunk.length > 1) {
          // remove merged nodes from children
          // 后面的节点已经合并进首节点，需从 children 中删掉。
          children.splice(currentIndex - currentChunk.length + 1, deleteCount)
          // also adjust index for the remaining cache items
          // 同时修正 context.cached 中后续缓存项的索引。
          const cacheIndex = context.cached.indexOf(
            currentChunk[currentChunk.length - 1]
              .codegenNode as CacheExpression,
          )
          if (cacheIndex > -1) {
            for (let i = cacheIndex; i < context.cached.length; i++) {
              const c = context.cached[i]
              if (c) c.index -= deleteCount
            }
            context.cached.splice(cacheIndex - deleteCount + 1, deleteCount)
          }
        }
      }
      // 返回删除的节点数，供外层遍历修正索引。
      return deleteCount
    }
    return 0
  }

  let i = 0
  for (; i < children.length; i++) {
    // 顺序扫描 children，寻找“连续可字符串化”的最大 chunk。
    const child = children[i]
    const isCached = isParentCached || getCachedNode(child)
    if (isCached) {
      // presence of cached means child must be a stringifiable node
      // 进一步分析这个节点本身是否真的满足字符串化条件。
      const result = analyzeNode(child as StringifiableNode)
      if (result) {
        // node is stringifiable, record state
        // 满足条件则累计统计值并收入当前 chunk。
        nc += result[0]
        ec += result[1]
        currentChunk.push(child as StringifiableNode)
        continue
      }
    }
    // we only reach here if we ran into a node that is not stringifiable
    // check if currently analyzed nodes meet criteria for stringification.
    // adjust iteration index
    // 一旦遇到不可合并节点，就尝试把前面积累的 chunk 落地。
    i -= stringifyCurrentChunk(i)
    // reset state
    // 然后重置状态，开始寻找下一段 chunk。
    nc = 0
    ec = 0
    currentChunk.length = 0
  }
  // in case the last node was also stringifiable
  // 收尾处理，避免最后一段 chunk 漏掉。
  stringifyCurrentChunk(i)
}

const getCachedNode = (
  node: TemplateChildNode,
): CacheExpression | undefined => {
  // 只有普通元素或 TextCall 且 codegenNode 已经是缓存表达式，才有资格参与。
  if (
    ((node.type === NodeTypes.ELEMENT &&
      node.tagType === ElementTypes.ELEMENT) ||
      node.type === NodeTypes.TEXT_CALL) &&
    node.codegenNode &&
      node.codegenNode.type === NodeTypes.JS_CACHE_EXPRESSION
  ) {
    return node.codegenNode
  }
}

// data-* / aria-* 即使不在已知属性表里，也允许被序列化。
const dataAriaRE = /^(?:data|aria)-/
const isStringifiableAttr = (name: string, ns: Namespaces) => {
  // 只有已知合法属性或 data/aria 属性，才能安全写进静态 HTML 字符串。
  return (
    (ns === Namespaces.HTML
      ? isKnownHtmlAttr(name)
      : ns === Namespaces.SVG
        ? isKnownSvgAttr(name)
        : ns === Namespaces.MATH_ML
          ? isKnownMathMLAttr(name)
          : false) || dataAriaRE.test(name)
  )
}

const isNonStringifiable = /*@__PURE__*/ makeMap(
  `caption,thead,tr,th,tbody,td,tfoot,colgroup,col`,
)

/**
 * for a cached node, analyze it and return:
 * - false: bailed (contains non-stringifiable props or runtime constant)
 * - [nc, ec] where
 *   - nc is the number of nodes inside
 *   - ec is the number of element with bindings inside
 */
function analyzeNode(node: StringifiableNode): [number, number] | false {
  // 这一层的任务不是“把节点转成字符串”，而是先保守判断：
  // 这棵静态子树是否足够安全，适合改写成 innerHTML 创建路径。
  // 某些表格相关标签依赖特殊解析上下文，不能直接 innerHTML 字符串化。
  if (node.type === NodeTypes.ELEMENT && isNonStringifiable(node.tag)) {
    return false
  }

  // v-once 节点有自己独立的缓存语义，不参与该优化。
  // v-once nodes should not be stringified
  if (node.type === NodeTypes.ELEMENT && findDir(node, 'once', true)) {
    return false
  }

  // TextCall 天然可字符串化，节点数 +1，带绑定元素数 +0。
  if (node.type === NodeTypes.TEXT_CALL) {
    return [1, 0]
  }

  // 当前元素本身先记一个节点数。
  let nc = 1 // node count
  // 只要这个元素有 props，就记为一个“带绑定的元素”。
  let ec = node.props.length > 0 ? 1 : 0 // element w/ binding count
  // 标记递归过程中是否发生 bailout。
  let bailed = false
  const bail = (): false => {
    bailed = true
    return false
  }

  // TODO: check for cases where using innerHTML will result in different
  // output compared to imperative node insertions.
  // probably only need to check for most common case
  // i.e. non-phrasing-content tags inside `<p>`
  function walk(node: ElementNode): boolean {
    // option 上的 value 有特殊运行时语义，要单独保守处理。
    const isOptionTag = node.tag === 'option' && node.ns === Namespaces.HTML
    for (let i = 0; i < node.props.length; i++) {
      const p = node.props[i]
      // bail on non-attr bindings
      if (
        p.type === NodeTypes.ATTRIBUTE &&
        !isStringifiableAttr(p.name, node.ns)
      ) {
        // 普通 attribute 但不是可安全序列化的属性，直接放弃。
        return bail()
      }
      if (p.type === NodeTypes.DIRECTIVE && p.name === 'bind') {
        // bail on non-attr bindings
        if (
          p.arg &&
          (p.arg.type === NodeTypes.COMPOUND_EXPRESSION ||
            (p.arg.isStatic && !isStringifiableAttr(p.arg.content, node.ns)))
        ) {
          // 动态参数或不可安全字符串化的属性名，放弃。
          return bail()
        }
        if (
          p.exp &&
          (p.exp.type === NodeTypes.COMPOUND_EXPRESSION ||
            p.exp.constType < ConstantTypes.CAN_STRINGIFY)
        ) {
          // 即便是静态树里的 v-bind，也要求表达式足够“可编译期求值”，
          // 否则就不能提前写死进 HTML 字符串。
          // 属性值如果不是足够稳定的常量表达式，也不能提前求值进字符串。
          return bail()
        }
        // <option :value="1"> cannot be safely stringified
        if (
          isOptionTag &&
          isStaticArgOf(p.arg, 'value') &&
          p.exp &&
          !p.exp.isStatic
        ) {
          // option 的动态 value 可能影响选中逻辑，保守放弃。
          return bail()
        }
      }
    }
    for (let i = 0; i < node.children.length; i++) {
      // 统计子节点数量。
      nc++
      const child = node.children[i]
      if (child.type === NodeTypes.ELEMENT) {
        // 子元素有 props 也算一个带绑定元素。
        if (child.props.length > 0) {
          ec++
        }
        // 递归检查子元素整棵子树。
        walk(child)
        if (bailed) {
          return false
        }
      }
    }
    return true
  }

  return walk(node) ? [nc, ec] : false
}

function stringifyNode(
  node: string | TemplateChildNode,
  context: TransformContext,
): string {
  // 真正进入 stringifyNode，说明 analyzeNode 已经做过一轮安全筛选；
  // 这里主要负责“如何序列化”，而不是“能不能序列化”。
  // 已经是普通字符串则原样返回。
  if (isString(node)) {
    return node
  }
  // symbol 在静态字符串里无意义，直接忽略。
  if (isSymbol(node)) {
    return ``
  }
  switch (node.type) {
    case NodeTypes.ELEMENT:
      // 元素节点递归转成 HTML 字符串。
      return stringifyElement(node, context)
    case NodeTypes.TEXT:
      // 文本节点需要做 HTML 转义。
      return escapeHtml(node.content)
    case NodeTypes.COMMENT:
      // 注释节点保留成 HTML 注释。
      return `<!--${escapeHtml(node.content)}-->`
    case NodeTypes.INTERPOLATION:
      // 插值节点必须先求常量值，再转义成文本。
      return escapeHtml(toDisplayString(evaluateConstant(node.content)))
    case NodeTypes.COMPOUND_EXPRESSION:
      // 复合表达式也尝试在编译期求值。
      return escapeHtml(evaluateConstant(node))
    case NodeTypes.TEXT_CALL:
      // TextCall 包了一层内容节点，继续递归。
      return stringifyNode(node.content, context)
    default:
      // static trees will not contain if/for nodes
      // 理论上静态树里不会出现 if/for；兜底返回空串。
      return ''
  }
}

function stringifyElement(
  node: ElementNode,
  context: TransformContext,
): string {
  // 先写开始标签。
  let res = `<${node.tag}`
  // 如果遇到 v-html / v-text，会改成直接填 innerHTML。
  let innerHTML = ''
  for (let i = 0; i < node.props.length; i++) {
    const p = node.props[i]
    if (p.type === NodeTypes.ATTRIBUTE) {
      // 普通静态属性直接序列化到标签上。
      res += ` ${p.name}`
      if (p.value) {
        res += `="${escapeHtml(p.value.content)}"`
      }
    } else if (p.type === NodeTypes.DIRECTIVE) {
      if (p.name === 'bind') {
        // 这里只处理已经被证明可以编译期求值的静态 v-bind。
        // 如果前面 analyzeNode 没放行，这里根本不会走到。
        // 这里只处理已经证明可静态求值的 v-bind。
        const exp = p.exp as SimpleExpressionNode
        if (exp.content[0] === '_') {
          // internally generated string constant references
          // e.g. imported URL strings via compiler-sfc transformAssetUrl plugin
          // 某些内部生成的资源 URL 常量需要保留占位符，稍后再还原成拼接表达式。
          res += ` ${
            (p.arg as SimpleExpressionNode).content
          }="__VUE_EXP_START__${exp.content}__VUE_EXP_END__"`
          continue
        }
        // #6568
        if (
          isBooleanAttr((p.arg as SimpleExpressionNode).content) &&
          exp.content === 'false'
        ) {
          // 布尔属性值为 false 时，序列化结果应直接省略该属性。
          continue
        }
        // constant v-bind, e.g. :foo="1"
        // 常量 v-bind 可以在编译期直接求值。
        let evaluated = evaluateConstant(exp)
        if (evaluated != null) {
          const arg = p.arg && (p.arg as SimpleExpressionNode).content
          if (arg === 'class') {
            // class 要先做标准化。
            evaluated = normalizeClass(evaluated)
          } else if (arg === 'style') {
            // style 要先 normalize，再转成 style 字符串。
            evaluated = stringifyStyle(normalizeStyle(evaluated))
          }
          res += ` ${(p.arg as SimpleExpressionNode).content}="${escapeHtml(
            evaluated,
          )}"`
        }
      } else if (p.name === 'html') {
        // #5439 v-html with constant value
        // not sure why would anyone do this but it can happen
        // 常量 v-html 直接作为 innerHTML 填入，不再递归 children。
        innerHTML = evaluateConstant(p.exp as SimpleExpressionNode)
      } else if (p.name === 'text') {
        // 常量 v-text 则先转显示文本，再写入 innerHTML。
        innerHTML = escapeHtml(
          toDisplayString(evaluateConstant(p.exp as SimpleExpressionNode)),
        )
      }
    }
  }
  // SFC scopeId 需要一并串到静态标签上。
  if (context.scopeId) {
    // SFC scoped 样式依赖 scopeId 属性，因此静态字符串化时也不能丢。
    res += ` ${context.scopeId}`
  }
  // 补全开始标签结束符。
  res += `>`
  if (innerHTML) {
    // 如果 v-html / v-text 已经决定了内部内容，直接写进去。
    res += innerHTML
  } else {
    // 否则递归序列化所有子节点。
    for (let i = 0; i < node.children.length; i++) {
      res += stringifyNode(node.children[i], context)
    }
  }
  // 非 void tag 才需要结束标签。
  if (!isVoidTag(node.tag)) {
    res += `</${node.tag}>`
  }
  return res
}

// __UNSAFE__
// Reason: eval.
// It's technically safe to eval because only constant expressions are possible
// here, e.g. `{{ 1 }}` or `{{ 'foo' }}`
// in addition, constant exps bail on presence of parens so you can't even
// run JSFuck in here. But we mark it unsafe for security review purposes.
// (see compiler-core/src/transforms/transformExpression)
function evaluateConstant(exp: ExpressionNode): string {
  // 这里只对已经被标记为“常量可求值”的表达式做最终求值，
  // 前面的 constType / bailout 判断已经把危险情况挡掉了。
  // 简单表达式直接通过 Function 求值。
  if (exp.type === NodeTypes.SIMPLE_EXPRESSION) {
    return new Function(`return (${exp.content})`)()
  } else {
    // compound
    // 复合表达式则把其中静态文本、插值和值表达式依次拼起来。
    let res = ``
    exp.children.forEach(c => {
      if (isString(c) || isSymbol(c)) {
        return
      }
      if (c.type === NodeTypes.TEXT) {
        res += c.content
      } else if (c.type === NodeTypes.INTERPOLATION) {
        // 插值节点递归求值后按显示文本规则拼接。
        res += toDisplayString(evaluateConstant(c.content))
      } else {
        // 其他表达式节点继续递归求值。
        res += evaluateConstant(c as ExpressionNode)
      }
    })
    return res
  }
}
