import { existsSync } from "node:fs";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { bundles } from "./bundles.js";

const projectRoot = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const workspaceRoot = resolve(projectRoot, "..");
const outRoot = join(projectRoot, "build", "node_modules");
const distRoot = join(projectRoot, "dist");

async function importFromPnpmStore(packagePath) {
  const fullPath = join(workspaceRoot, "node_modules", ".pnpm", packagePath);
  if (!existsSync(fullPath)) {
    throw new Error(`Cannot find Rollup dependency in pnpm store: ${fullPath}`);
  }
  return import(pathToFileURL(fullPath).href);
}

async function importPackage(specifier, fallbackStorePath) {
  try {
    return await import(specifier);
  } catch (error) {
    if (error?.code !== "ERR_MODULE_NOT_FOUND") {
      throw error;
    }
    return importFromPnpmStore(fallbackStorePath);
  }
}

const { rollup } = await importPackage("rollup", "rollup@4.61.1/node_modules/rollup/dist/es/rollup.js");
const { default: alias } = await importPackage(
  "@rollup/plugin-alias",
  "@rollup+plugin-alias@5.1.1_rollup@4.61.1/node_modules/@rollup/plugin-alias/dist/es/index.js",
);
const { nodeResolve } = await importPackage(
  "@rollup/plugin-node-resolve",
  "@rollup+plugin-node-resolve@16.0.3_rollup@4.61.1/node_modules/@rollup/plugin-node-resolve/dist/es/index.js",
);
const { default: commonjs } = await importPackage(
  "@rollup/plugin-commonjs",
  "@rollup+plugin-commonjs@28.0.9_rollup@4.61.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js",
);

const aliasEntries = [
  ["shared", "packages/shared/index.js"],
  ["react", "packages/react/src/index.js"],
  ["react/jsx-runtime", "packages/react/src/jsx-runtime.js"],
  ["react/jsx-dev-runtime", "packages/react/src/jsx-dev-runtime.js"],
  ["react-dom", "packages/react-dom/src/shared/ReactDOM.js"],
  ["react-dom/client", "packages/react-dom/src/client/ReactDOMClient.js"],
  ["react-reconciler", "packages/react-reconciler/src/ReactFiberReconciler.js"],
  ["react-dom-bindings", "packages/react-dom-bindings/src/index.js"],
  ["scheduler", "packages/scheduler/src/index.js"],
  ["react-is", "packages/react-is/src/index.js"],
  ["react-cache", "packages/react-cache/src/index.js"],
  ["use-sync-external-store", "packages/use-sync-external-store/src/index.js"],
  ["use-subscription", "packages/use-subscription/src/index.js"],
].map(([find, replacement]) => ({
  find,
  replacement: join(distRoot, replacement),
}));

function distSubpath(packageName, subpath) {
  return join(distRoot, "packages", packageName, subpath);
}

function resolverPlugin() {
  return {
    name: "front-react-workspace-resolver",
    resolveId(source) {
      const mappings = [
        ["shared/", "shared", ""],
        ["react-reconciler/", "react-reconciler", ""],
        ["react-dom-bindings/", "react-dom-bindings", ""],
        ["scheduler/", "scheduler", "src/"],
        ["react/", "react", ""],
        ["react-dom/", "react-dom", ""],
        ["use-sync-external-store/", "use-sync-external-store", ""],
      ];

      for (const [prefix, packageName, injectedPrefix] of mappings) {
        if (source.startsWith(prefix) && source.endsWith(".js")) {
          const relative = source.slice(prefix.length);
          return distSubpath(packageName, `${injectedPrefix}${relative}`);
        }
      }
      return null;
    },
  };
}

function banner(label) {
  return [
    "/**",
    " * @front/react-source rollup bundle",
    ` * entry: ${label}`,
    " * Generated by scripts/rollup/build.js.",
    " */",
    "",
  ].join("\n");
}

async function copyTypes(bundle) {
  for (const [from, to] of bundle.types ?? []) {
    const fromPath = join(projectRoot, from);
    if (!existsSync(fromPath)) {
      continue;
    }
    const toPath = join(outRoot, bundle.packageName, to);
    await mkdir(dirname(toPath), { recursive: true });
    await cp(fromPath, toPath);
  }
}

async function writePackageJson(bundle) {
  const packageRoot = join(outRoot, bundle.packageName);
  await mkdir(packageRoot, { recursive: true });
  const packageJsonPath = join(packageRoot, "package.json");
  if (existsSync(packageJsonPath)) {
    return;
  }

  const mainFile =
    bundle.packageName === "react-dom"
      ? "index.js"
      : "index.js";
  const packageJson = {
    name: bundle.packageName,
    version: "0.0.1-front-source",
    type: "module",
    main: mainFile,
    module: mainFile,
    types: "index.d.ts",
    private: true,
  };
  await writeFile(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);
}

async function buildBundle(bundle) {
  const input = join(projectRoot, bundle.input);
  if (!existsSync(input)) {
    throw new Error(`Missing Rollup input for ${bundle.label}: ${input}`);
  }

  const rollupBundle = await rollup({
    input,
    external: [],
    onwarn(warning, warn) {
      if (warning.code === "CIRCULAR_DEPENDENCY") {
        return;
      }
      warn(warning);
    },
    plugins: [
      resolverPlugin(),
      alias({ entries: aliasEntries }),
      nodeResolve({
        extensions: [".js"],
        modulePaths: [join(projectRoot, "dist", "packages")],
      }),
      commonjs(),
    ],
  });

  for (const output of bundle.files) {
    const file = join(outRoot, bundle.packageName, output.file);
    await mkdir(dirname(file), { recursive: true });
    await rollupBundle.write({
      file,
      format: output.format,
      exports: "named",
      sourcemap: true,
      banner: banner(bundle.label),
    });
    console.log(`  ${bundle.label} -> ${file.replace(`${projectRoot}/`, "")}`);
  }

  await rollupBundle.close();
  await copyTypes(bundle);
  await writePackageJson(bundle);
}

async function main() {
  await rm(join(projectRoot, "build"), { recursive: true, force: true });
  await mkdir(outRoot, { recursive: true });

  console.log("Building @front/react-source bundles with Rollup");
  for (const bundle of bundles) {
    await buildBundle(bundle);
  }

  const manifest = {
    generatedAt: new Date().toISOString(),
    bundles: bundles.map((bundle) => bundle.label),
  };
  await writeFile(join(projectRoot, "build", "build-info.json"), `${JSON.stringify(manifest, null, 2)}\n`);

  const buildInfo = await readFile(join(projectRoot, "build", "build-info.json"), "utf8");
  console.log(`Wrote build/build-info.json\n${buildInfo.trim()}`);
}

await main();
