/**
 * 文件作用：runtime-core 的辅助函数模块。
 *
 * 当前文件 renderSlot.ts 负责承接编译产物 `<slot />` 的运行时渲染逻辑。
 *
 * 它会在当前组件的标准化 slots 容器里查找对应插槽函数，
 * 然后把结果包装成 Fragment VNode，交回渲染器继续 patch。
 */

import type { Data } from '../component'
import type { RawSlots, Slots } from '../componentSlots'
import {
  type ContextualRenderFn,
  currentRenderingInstance,
} from '../componentRenderContext'
import {
  Comment,
  Fragment,
  type VNode,
  type VNodeArrayChildren,
  createBlock,
  createVNode,
  isVNode,
  openBlock,
} from '../vnode'
import { PatchFlags, SlotFlags, isSymbol } from '@vue-source/shared'
import { warn } from '../warning'
import { isAsyncWrapper } from '../apiAsyncComponent'

/**
 * 渲染 `<slot />` 的运行时辅助函数。
 *
 * 主要功能：
 * - 根据插槽名找到对应 slot 函数
 * - 用传入的 `props` 调用该 slot
 * - 如果没有有效内容，则退回到 fallback
 * - 最终把插槽内容包装成一个 Fragment VNode 返回给渲染器
 *
 * 参数：
 * - `slots`：当前组件实例上的标准化 slots 容器
 * - `name`：要渲染的插槽名
 * - `props`：传给作用域插槽的参数
 * - `fallback`：当插槽不存在或内容为空时的回退内容生成函数
 * - `noSlotted`：是否跳过 slotted scopeId 处理
 *
 * 依赖：
 * - `componentSlots.ts` 负责把原始 slots 预处理成这里能直接调用的函数
 * - `createBlock / createVNode` 负责把插槽结果重新包装成 VNode
 */
export function renderSlot(
  slots: Slots,
  name: string,
  props: Data = {},
  // this is not a user-facing function, so the fallback is always generated by
  // the compiler and guaranteed to be a function returning an array
  fallback?: () => VNodeArrayChildren,
  noSlotted?: boolean,
): VNode {
  if (
    currentRenderingInstance!.ce ||
    (currentRenderingInstance!.parent &&
      isAsyncWrapper(currentRenderingInstance!.parent) &&
      currentRenderingInstance!.parent.ce)
  ) {
    const hasProps = Object.keys(props).length > 0
    // in custom element mode, render <slot/> as actual slot outlets
    // wrap it with a fragment because in shadowRoot: false mode the slot
    // element gets replaced by injected content
    if (name !== 'default') props.name = name
    return (
      openBlock(),
      createBlock(
        Fragment,
        null,
        [createVNode('slot', props, fallback && fallback())],
        hasProps ? PatchFlags.BAIL : PatchFlags.STABLE_FRAGMENT,
      )
    )
  }

  let slot = slots[name]

  if (__DEV__ && slot && slot.length > 1) {
    warn(
      `SSR-optimized slot function detected in a non-SSR-optimized render ` +
        `function. You need to mark this component with $dynamic-slots in the ` +
        `parent template.`,
    )
    slot = () => []
  }

  // a compiled slot disables block tracking by default to avoid manual
  // invocation interfering with template-based block tracking, but in
  // `renderSlot` we can be sure that it's template-based so we can force
  // enable it.
  if (slot && (slot as ContextualRenderFn)._c) {
    ;(slot as ContextualRenderFn)._d = false
  }
  openBlock()
  const validSlotContent = slot && ensureValidVNode(slot(props))
  const slotKey =
    props.key ||
    // slot content array of a dynamic conditional slot may have a branch
    // key attached in the `createSlots` helper, respect that
    (validSlotContent && (validSlotContent as any).key)
  const rendered = createBlock(
    Fragment,
    {
      key:
        (slotKey && !isSymbol(slotKey) ? slotKey : `_${name}`) +
        // #7256 force differentiate fallback content from actual content
        (!validSlotContent && fallback ? '_fb' : ''),
    },
    validSlotContent || (fallback ? fallback() : []),
    validSlotContent && (slots as RawSlots)._ === SlotFlags.STABLE
      ? PatchFlags.STABLE_FRAGMENT
      : PatchFlags.BAIL,
  )
  if (!noSlotted && rendered.scopeId) {
    rendered.slotScopeIds = [rendered.scopeId + '-s']
  }
  if (slot && (slot as ContextualRenderFn)._c) {
    ;(slot as ContextualRenderFn)._d = true
  }
  return rendered
}

/**
 * 检查插槽返回值里是否存在“真正可渲染的节点”。
 *
 * 作用：
 * - 过滤掉只包含注释节点、空 Fragment 的情况
 * - 如果整组内容都等价于“空”，则返回 `null`
 *
 * 这样 `renderSlot` 就能正确决定是否应该回退到 fallback。
 */
export function ensureValidVNode(
  vnodes: VNodeArrayChildren,
): VNodeArrayChildren | null {
  return vnodes.some(child => {
    if (!isVNode(child)) return true
    if (child.type === Comment) return false
    if (
      child.type === Fragment &&
      !ensureValidVNode(child.children as VNodeArrayChildren)
    )
      return false
    return true
  })
    ? vnodes
    : null
}
